### PR TITLE
Fix storage updates performed by the ocm-clusters integration

### PR DESCRIPTION
**Pull request by steveteahan**
app-interface uses the 'storage' key and OCM uses the 'storage_quota'
key. Using the wrong key to parse the a-i spec was result in discarding
any storage changes. There are some other changes that can be made here
to ensure that an empty cluster spec patch doesn't occur silently, but
that will be handled in a separate PR.

For additional testing, I added some logging at the beginning/end of the `update_cluster` method.

```
# Before the change
## Input
{'storage': 4100} 
## Output (what we sent to patch)
{}

# After the change
## Input
{'storage': 4100}
## Output (what we sent to patch)
{'storage_quota': {'value': 4402341478400.0}}
```

### CODE REVIEW

**Comment by steveteahan** [comment]
Longer-term fix can be evaluated in this ticket: https://issues.redhat.com/browse/APPSRE-4018

**Review by jfchevrette — APPROVED** [review]
LGTM

**Comment by maorfr** [comment]
not sure it needs changing, but did you see `ALLOWED_SPEC_UPDATE_FIELDS`?

**Comment by steveteahan** [comment]
> not sure it needs changing, but did you see `ALLOWED_SPEC_UPDATE_FIELDS`?

Yes, from what I'm seeing there, we're evaluating the app-interface cluster spec (storage) and not the OCM spec (storage_quota).

**Pull request merged**
