### PR TITLE
handle errors thrown during reconcile run

### PR DESCRIPTION
**Pull request by BumbleFeng**

### CODE REVIEW

**Comment by tparikh** [comment]
LGTM

**Comment by apahim** [comment]
This will wake people up. I thought we would select which integrations should page us... Cc @tparikh

**Comment by tparikh** [comment]
@apahim The integration has already failed at this point. We are just catching the exception and logging a better message instead of the stack trace.

**Comment by apahim** [comment]
Yes, the unhandled exception had the potential to CrashLoop the integration. That is what wakes us up. Now we're handling the exception but it can still provoke the CrashLoop. Anyway, that's probably a different discussion.

**Pull request merged**
