### PR TITLE
fix pylint missing-timeout

### PR DESCRIPTION
**Pull request by BumbleFeng**
add in https://github.com/PyCQA/pylint/releases/tag/v2.15.0

Signed-off-by: Feng Huang <fehuang@redhat.com>

### CODE REVIEW

**Comment by steveteahan** [comment]
Are there many instances of this? I'd prefer to ignore inline if not because this is a very common cause of issues. The default is no timeout which can lead to calls hanging for a very long time.

**Comment by BumbleFeng** [comment]
about 30 instances. Do you have a suggestion for timeout value? I can just fix them all.

**Comment by steveteahan** [comment]
I usually default to something like 60 seconds unless there is a good reason to have a lower value. Fixing these and keeping the check disabled is best if you have the time. If not, we can disable it per file by adding `# pylint: disable=missing-timeout` at the top of the file. Both would result in a much better chance of catching this issue going forward for new code, rather than having to disable at the project level.

Thanks for doing this!

**Review by steveteahan — APPROVED** [review]
Thanks again!

**Pull request merged**
