### PR TITLE
tweak APP_INTERFACE_PROJECT_ID for internal integrations

### PR DESCRIPTION
**Pull request by maorfr**
follow up to #1552

### CODE REVIEW

**Comment by rporres** [comment]
what is this `APP_INTERFACE_PROJECT_ID` for?

**Comment by maorfr** [comment]
https://github.com/app-sre/qontract-reconcile/blob/master/reconcile/cli.py

**Comment by rporres** [comment]
`gitlab_project_id`?

**Comment by maorfr** [comment]
what about this? https://github.com/app-sre/qontract-reconcile/blob/c917dcfaebd58d02031440b8b4aced2ad546f312/helm/qontract-reconcile/values-internal.yaml#L237

**Comment by rporres** [comment]
great, thx

**Pull request merged**
