### PR TITLE
Run ocm.update_cluster in dry-run

### PR DESCRIPTION
**Pull request by esron**
Ticket: [APPSRE-2938](https://issues.redhat.com/browse/APPSRE-2938)

### CODE REVIEW

**Review by maorfr — CHANGES_REQUESTED** [review]
the idea would be to call the OCM update cluster endpoint (PATCH /clusters/{id}) with the dryRun query parameter.

**Comment by OliviaHY** [comment]
LGTM. @maorfr Could you please take another look?

**Review by maorfr — APPROVED** [review]
beautiful. LGTM

**Pull request merged**
