### PR TITLE
Convert container base form centos:7 to ubi8:8.2

### PR DESCRIPTION
**Pull request by arilivigni**
Made some modifications to support going from centos:7 to ubi8:8.2 for the base image

### CODE REVIEW

**Comment by arilivigni** [comment]
> we should test all our integrations with this change.
> an easy way to do that is to run `make rc`, which will create a new image with these changes (and push it to quay).
> you can then create a MR to app-interface (DO NOT MERGE) with the new image, to see how the integrations are responding.

excellent will do!

**Comment by arilivigni** [comment]
@maorfr can this be merged then?

**Comment by maorfr** [comment]
this has been tested in https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/10879.

LGTM from me, but i would still want @jfchevrette to take a look. i don't feel comfortable approving this as i have never used the ubi image myself.

**Review by jfchevrette — APPROVED** [review]

**Comment by jfchevrette** [comment]
LGTM as well. Test results look good 👍

**Pull request merged**
