### PR TITLE
allow config file to be defined through environment variable

### PR DESCRIPTION
**Pull request by maorfr**
i never want to type `--config` again.

### CODE REVIEW

**Review by patjlm — APPROVED** [review]
LGTM

**Comment by patjlm** [comment]
I was going to mention we could have the same in qontract-cli 😃

**Comment by patjlm** [comment]
> I was going to mention we could have the same in qontract-cli 😃

or does it use the same @config_file already ?

**Comment by maorfr** [comment]
same one indeed!
https://github.com/app-sre/qontract-reconcile/blob/747b0d85a43ec60b08a23793650cc5c3ba2f8fd1/tools/qontract_cli.py#L30

**Pull request merged**
