### PR TITLE
BUGFIX: Identical resources need to be checked for take_overs and saas deprectations

### PR DESCRIPTION
**Pull request by lechuk47**
## Description 

Fixes a bug where moving resources between saas files was not failing in pr-checks. This was only happening for non-changing resources because they were not being checked. 

APPSRE-8659

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at db020a6</samp>

*  Add new feature to allow taking over or deprecating identical resources ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fR674-R741), [link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fL878-R962))
  - Define `should_take_over` function to check if a caller can take over a resource from another caller based on the `options` argument ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fR674-R741))
  - Define `handle_identical_resources` function to compare the current and desired states of identical resources and apply the take over or deprecation logic ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fR674-R741))
  - Call `handle_identical_resources` before `handle_new_resources` in `_realize_resource_data_3way_diff` to ensure the correct order of operations ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fL878-R962))
*  Improve logging message formatting in `apply` function ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fL603-R604))
  - Split a long message into two lines for readability ([link](https://github.com/app-sre/qontract-reconcile/pull/3955/files?diff=unified&w=0#diff-a14858c214c6abf739ca222b3450b66851c93a7a407d27cb9dff88979dfc043fL603-R604))

### CODE REVIEW

**Comment by esron** [comment]
Don't we need tests for that?

**Comment by lechuk47** [comment]
> Don't we need tests for that?

Testing this is quite hard and there is much work to consider. I can open a ticket to add tests to the whole openshift_saas_deploy workflow but I would like to add this fix to prevent this situation. 

I've tested this locally and the logic is almost the same as in the modified_resources handling.

**Comment by lechuk47** [comment]
> Don't we need tests for that?

Added tests for take overs on identical and modified resources. PTAL

**Review by esron — APPROVED** [review]

**Comment by maorfr** [comment]
:heart:

**Pull request merged**
