### PR TITLE
Bump oc version to 4.10.15

### PR DESCRIPTION
**Pull request by chassing**

### CODE REVIEW

**Review by maorfr — APPROVED** [review]
LGTM

please make the team aware of this change, as this impacts everyone's local development environment as well

**Review by rporres — COMMENTED** [review]
Please upgrade `Dockerfile.test` too when you have upgraded `qontract-reconcile-builder`

**Comment by chassing** [comment]
@rporres please approve https://github.com/app-sre/container-images/pull/47 and I'll update this PR afterwards

**Review by geoberle — APPROVED** [review]
lgtm

**Pull request merged**
