### PR TITLE
[openshift-resources] add support for openshift shared resources

### PR DESCRIPTION
**Pull request by maorfr**
Part of https://issues.redhat.com/browse/APPSRE-2524

Dpends on https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/9822

Now that we are running multiple instances of the same service, we are duplicating a lot of the content of a namespace file. Mostly we are duplicating the openshift resources that we want to apply to the namespace.

This PR allows users to define shared resources that can be added to multiple namespace files, thus removing the need to duplicate this content and allow users to update all their namespaces in a single place.

The lack in this ability recently led to 2 namespace files overriding each other and causing a service misconfiguration.

### CODE REVIEW

**Review by apahim — APPROVED** [review]
THis is AWESOME. I was afraid things would get fuzzy, but kept a very clear distinction about what's shared and what's local. Kudos.

**Review by aditya-konarde — APPROVED** [review]
Lgtm! :)

**Comment by rporres** [comment]
Arrived late to the party but read it anyway. LGTM, indeed!

**Comment by maorfr** [comment]
thank you all!

**Pull request merged**
