### PR TITLE
openshift-saas-deploy to use Github token

### PR DESCRIPTION
**Pull request by apahim**

### CODE REVIEW

**Comment by maorfr** [comment]
I know I did it in the past, but I don't like it :)

Totally good enough for now and to enable github-mirror authentication!

**Comment by apahim** [comment]
Sorry, what's it you don't like?

**Comment by maorfr** [comment]
sorry, this:
```
token = github_config['app-sre']['token']
```

using the `app-sre` token explicitly...

**Comment by apahim** [comment]
Got it. It's actually not working. Let me do it the right way.

**Pull request merged**
