### PR TITLE
Remove stacked retry() calls in secrets_reader

### PR DESCRIPTION
**Pull request by lechuk47**
Stacked `@retry` definitions multiply the retry attempts for a function call. 

```python 
@retry()  
def func1():
  func2()
 
@retry() 
def func2():
  do_stuff
 ```

`retry` has a default `max_attemps=3`. In case of failure in `func2`, `func1` will be retried 9 times.

### CODE REVIEW

**Review by fishi0x01 — APPROVED** [review]
My only concern is that Im not sure all consumers are currently adding their own retries. But I agree that this is sth that should either way be defined on consumer side and that this should be the common approach.

**Comment by fishi0x01** [comment]
Still wondering if we should get some more opinions on this one

**Review by hemslo — APPROVED** [review]
LGTM! If we just want to retry on request error, can use `HTTPAdapter(max_retries=x)` to replace `@retry` for `_VaultClient` too.

**Comment by lechuk47** [comment]
> My only concern is that Im not sure all consumers are currently adding their own retries. But I agree that this is sth that should either way be defined on consumer side and that this should be the common approach.

All the `retry()` calls I have removed have a `retry()` in the call to vault. 

I also think the retry calls should be in the top calls (this way, the retry parameters can be changed in every specific case) but I'm not sure every caller have a retry defined.

**Pull request merged**
