### PR TITLE
New integration: GCR-Mirror

### PR DESCRIPTION
**Pull request by apahim**
https://gitlab.cee.redhat.com/service/app-interface/merge_requests/5135

### CODE REVIEW

**Comment by apahim** [comment]
Not clear whether we are going to use this, but leaving here for readyness.

**Comment by maorfr** [comment]
@apahim can we create a `ecr-mirror` integration? it will be so much simpler instead of what we're doing right now, which is push an image to ECR in the build-master job.

**Comment by maorfr** [comment]
this is a great idea btw! :)

**Comment by apahim** [comment]
@maor we sure can. working on it.

**Comment by maorfr** [comment]
@apahim scratch that, we'll keep doing the "mirror" via the build-master job.

**Comment by apahim** [comment]
@maor, the commit is ready. we can decide whether or not to use it :)

**Comment by maorfr** [comment]
i am not @maor, leave the guy alone :)

**Comment by apahim** [comment]
lool

**Pull request merged**
