### PR TITLE
enable blacks' truthy-bool and redundant-expr checks

### PR DESCRIPTION
**Pull request by chassing**
This enables blacks' `truthy-bool` and `redundant-expr` checks.

* for a detailed explanation of `truthy-bool` see this [blog post](https://adamj.eu/tech/2022/10/24/python-type-hints-truthy-bool/)
* and for `redundant-expr` see the [official one](https://mypy.readthedocs.io/en/stable/error_code_list2.html#check-that-expression-is-redundant-redundant-expr)

### CODE REVIEW

**Review by janboll — APPROVED** [review]
LGTM, did you run all the integrations?

**Comment by chassing** [comment]
No, I didn't run any integration; I trust black :) The only "complicated" parts are the removed `if`s, but here I had an extra look

**Comment by geoberle** [comment]
to be honest this scares me a lot! i don't trust black to that extend. reformatting sure why not. but this ...

**Comment by chassing** [comment]
Sorry I meant "mypy" not black

**Comment by geoberle** [comment]
oh so you did these changes manually? i'm relieved again :)

**Comment by chassing** [comment]
Yes, I've activated the additional mypy checks and updated the code manually :)

**Pull request merged**
