### PR TITLE
Validate container names against DNS-1123 in OpenshiftResource

### PR DESCRIPTION
**Pull request by jfchevrette**
This PR adds validation for container names in OpenshiftResource. Corresponding tests have also been added.

This also extracts the DNS-1123 based regexes as global variables so they can be reused elsewhere in the future.

I have also changed the error messages slightly for clarity and added a link to the kubernetes docs on object naming

### CODE REVIEW

**Comment by BumbleFeng** [comment]
There is also a lengthy limit, IIRC

**Comment by jfchevrette** [comment]
Please hold on reviewing this PR I will change it to do the validation in openshift_base rather than locally in the sql-query integration

**Comment by maorfr** [comment]
i agree with adding this to our integrations. until this is solved, we can put a patch in place: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/14081

**Comment by jfchevrette** [comment]
I've refactored the PR and updated the description accordingly. The validation is now done in OpenshiftResource itself so this should catch issues globally.

**Comment by jfchevrette** [comment]
Added length checks and tests covering all objects names tests we have right now

**Comment by rporres** [comment]
Is this ready to review, @jfchevrette . It definitely looks to me :)

**Review by rporres — APPROVED** [review]
LGTM... And with updated tests <3

**Pull request merged**
