### PR TITLE
Make jenkins-webhooks a StatefulSet

### PR DESCRIPTION
**Pull request by rporres**
Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

### CODE REVIEW

**Comment by rporres** [comment]
This hasn't been tested yet

**Review by maorfr — APPROVED** [review]
LGTM as is

just a nit - i usually prefer something more abstract like `cache: true` instead of templating out specific implementation (like `Deployment`). good to merge as is, up to you.

**Comment by rporres** [comment]
I like both approaches, I don't think any good argument against yours except of reworking the files 😂  Since you like one more, I'll go with it 😉

**Comment by rporres** [comment]
It's true that it looks cleaner and nicer :-D

**Pull request merged**
