### PR TITLE
bug fix: can not create DB with enhanced_monitoring

### PR DESCRIPTION
**Pull request by bkez322**
https://issues.redhat.com/browse/APPSRE-3511

This PR is intended to fix a bug causing new Terraform-managed RDS instance provisioning to fail if the "enhanced_monitoring" flag is enabled.

The prior workaround flow has been to perform 2 separate changes (1 to create RDS instance, 1 to enable 'enhanced_monitoring'). This bug fix should allow a single change to achieve the same thing.

The code currently correctly ensures that the enhanced-monitoring-iam-role-policy-attachment tf-resource "depends on" the enhanced-monitoring-iam-role. What the code currently **does not do** is ensure that a new RDS instances using enhanced-monitoring "depends on" a enhanced-monitoring-iam-role-policy-attachment tf-resource. This PR fixes that bug.

### CODE REVIEW

**Comment by bkez322** [comment]
(This PR branch used to include a lot of refactoring, but I moved the refactoring to a [different PR](https://github.com/app-sre/qontract-reconcile/pull/1820))

**Review by maorfr — APPROVED** [review]
LGTM

Love the split to 2 PRs! Made this review so simple!

**Review by Piojo — APPROVED** [review]
LGTM

**Comment by bkez322** [comment]
As documented in the Jira ticket, I've since learned that this PR doesn't actually do anything to fix the issue described.

Because of this will:
* close this PR without merging
* Move some of the changes of this of this PR into [a separate, small refactoring oriented PR](https://github.com/app-sre/qontract-reconcile/pull/1843)
* Open another new PR that actually fixes the issue for real (COMING SOON™)

**Pull request closed without merging**
