### PR TITLE
add support for role expiration to all integrations

### PR DESCRIPTION
**Pull request by maorfr**
follows up on:
- #2125
- #2033

this PR adds support for role expiration for all remaining integrations which are calculating their desired state based on roles.

### CODE REVIEW

**Review by geoberle — COMMENTED** [review]
LGTM - i like the filter approach in the query!

**Comment by suzana-nesic** [comment]
LGTM as well! I really like the refactoring :) 
I'm going to add a couple of suggestions that will allow the tests to pass.

**Comment by suzana-nesic** [comment]
It seems like Github doesn't have a feature where you can add suggestions on files that are not part of the pull request but within [here](https://github.com/maorfr/qontract-reconcile/blob/dddfb5a80f6fb9229b3d046af365558d7b83c914/reconcile/test/fixtures/quay_membership/desired_state_simple.yml#L14) and [here](https://github.com/maorfr/qontract-reconcile/blob/dddfb5a80f6fb9229b3d046af365558d7b83c914/reconcile/test/fixtures/github_org/desired_state_simple.yml#L12), if you add the line `expirationDate:` without any value assigned to it, that will allow the tests to pass

**Comment by maorfr** [comment]
@suzana-nesic done! thanks a lot!
would you like to take another look?

**Comment by suzana-nesic** [comment]
Absolutely, looks perfect! :D

**Comment by maorfr** [comment]
So approve the PR!

**Comment by suzana-nesic** [comment]
You want me to do the famous squash and merge?

**Review by suzana-nesic — APPROVED** [review]
LGTM

**Pull request merged**
