### PR TITLE
change log value

### PR DESCRIPTION
**Pull request by BumbleFeng**
Change logs config in the Helm chart file. Prepare to ship logs to additional providers

https://issues.redhat.com/browse/APPSRE-1618

### CODE REVIEW

**Comment by maorfr** [comment]
w00t w00t! your first PR!

The intention is to use a separate sidecar for each location we want to ship logs to.
Your changes seem as if we plan to re-use the existing sidecar/initcontainer, which is a bit different.

In addition, does this pass `make generate`? (you'll need to install the helm 3 binary and call it `helm3`).

Let's also enhance the PR description a bit to indicate what these changes are. You did reference the Jira ticket, which is great, but let's add a description here as well.

**Comment by mmclanerh** [comment]
@BumbleFeng  first PR! so cool! :D

**Comment by maorfr** [comment]
@BumbleFeng please run `make generate` and commit that as well

**Comment by maorfr** [comment]
@BumbleFeng can you please rebase on top of latest `master`?

**Pull request merged**
