### PR TITLE
[rhidp] get enabled OCM orgs via query instead via cli option

### PR DESCRIPTION
**Pull request by chassing**
Prepare move of the RHIDP integrations to the sre-capabilities repo. The sre-capabilities repo now supports OCM organizations; therefore, use them instead of the `--ocm-org-ids` command line option.

Ticket: [APPSRE-8609](https://issues.redhat.com/browse/APPSRE-8609)

### CODE REVIEW

**Comment by TGPSKI** [comment]
`--ocm-org-ids` - only consumed in RHIDP / sre-capabilities context?

**Comment by chassing** [comment]
> `--ocm-org-ids` - only consumed in RHIDP / sre-capabilities context?

I don't understand your question.

**Review by geoberle — APPROVED** [review]
awesome, thanks!

**Comment by TGPSKI** [comment]
> > `--ocm-org-ids` - only consumed in RHIDP / sre-capabilities context?
> 
> I don't understand your question.

Apologies.  Asked another way:

This code change removes a CLI option that is available to any user of qontract-cli. I was curious - are there any established use cases for the `--ocm-org-ids` flag besides for sre-capabilities?

**Pull request merged**
