### PR TITLE
[qontract-cli] add get app-interface-merge-history command

### PR DESCRIPTION
**Pull request by maorfr**
this command (running in app-interface-output) will allow us to look into intervals between merges to get an understanding of how slow/fast things are going.

this is a complement to `qontract-cli get app-interface-merge-queue`.

### CODE REVIEW

**Comment by maorfr** [comment]
app-interface-output MR: https://gitlab.cee.redhat.com/service/app-interface-output/-/merge_requests/20

**Comment by rporres** [comment]
So you're just getting the last 100, right? Every time we run it, we will get potentially a lot of merge requests that were in the previous run and there's a slight possibility that if we run not enough frequently, we miss something.

How about adding a date so that we know how many have been merged since a moment in time instead of the arbitrary 100? We will then be able to avoid overlaps

**Comment by rporres** [comment]
ok, so you're rewriting the whole thing with each run and you will see the "MERGED_AT" column to get the idea.

**Review by rporres — APPROVED** [review]
Ok, so you rewrite each time the final page and you take a look into the `MERGED_AT` column to get an idea of the speed...

I'm not sure how useful will be since I guess it would be interesting to compare days, etc.. But it is out of the scope of the MR. Let's try this.

**Pull request merged**
