### PR TITLE
[WIP] New integration: openshift-clusterrolebinding

### PR DESCRIPTION
**Pull request by jfchevrette**
This is a first stab at a ClusterRoleBinding integration

This allows setting ClusterRoleBindings under a cluster definition as such:
```yaml
clusterRoleBindings:
- name: testjfc
  roleRef:
    name: testjfc
  subjects:
  - kind: ServiceAccount
    name: my-sa
    namespace: my-ns
  userNames:
  - system:serviceaccount:my-ns:my-sa
- name: my-cool-crb
  roleRef:
    name: my-cool-cr
  subjects:
  - kind: User
    name: foo
  - kind: User
    name: bar
  userNames:
  - foo
  - bar
```

It uses the usual openshift_resources functions so qontract annotations are set. It'll happily start to manage existing ClusterRoleBindings if told to.

Notes for reviewers:
- I did some not-so-greatcode gymnastics in `utils/oc.py` and `utils/openshift_resource.py` where I check or set the namespace name to `_` (underscore) for global/cluster-scoped resources to avoid having to do a larger refactor.
- I had to refactor `fetch_current_state` and `init_specs_to_fetch` to teach them how to handle cluster-scoped resources. I think I've updated all code that used these functions.

### CODE REVIEW

**Comment by maorfr** [comment]
the change in openshift_base to handle both namespaces and clusters looks good.
setting the namespace to `_` for now seems reasonable, we can refactor namespace to be a kv arg or anything else later. for sure outside the scope of this PR.

i love all the reusing you did!

i think the approach you selected to define the ClusterRoleBindings in the schema is solid and isolated (as in, nothing else has to be defined in app-interface for this to work), i like that.

i just wanted to comment that it is very different from how we handle RoleBindings, which is probably fine, but i suppose we may want them to be more similar? we just did a major refactor with RoleBindings, here is an example:
https://gitlab.cee.redhat.com/service/app-interface/blob/master/data/teams/app-sre/roles/app-sre-managed-namespaces-admin.yml#L9

wdyt?

overall this is very nice work!

**Comment by jfchevrette** [comment]
@maorfr I originally though we could refactor the RoleBinding integration in a similar (almost identical) way to the ClusterRoleBinding one. Both are using the same `roleRef` schema in the k8s API so effectively both could be managed the same, with the exception that one is namespace-scoped and the other is cluster-scoped.

For now I'm going to merge this and we can revisit this at a later time

**Comment by jfchevrette** [comment]
@maorfr I've pushed a change in 4d0258c that will prevent overwriting existing ClusterRoleBinding objects that don't already have the qontract-reconcile annotations. A message will be shown:

```
ERROR: [app-sre] resource 'ClusterRoleBinding/cluster-readers' present w/o annotations. Refusing to overwrite an unmanaged ClusterRoleBinding
ERROR: One or more desired ClusterRoleBinding object already exist on the cluster without qontract-reconcile annotations. If you are sure you want to override it you can add the qontract-reconcile annotation manually and run the integration again.
```

**Comment by maorfr** [comment]
We've had that initially with openshift-resources and ended up automatically taking over. I think we should keep consistency around that. Wdyt?

**Comment by maorfr** [comment]
And LGTM, merge at will and we can iterate!

**Comment by maorfr** [comment]
we should also consider the case when a user is deleted from app-interface (how will we remove his ClusterRoleBindings)

**Comment by jfchevrette** [comment]
I will re-do this change and mimic what we're doing for regular RoleBindings.

**Pull request closed without merging**
