### PR TITLE
use threaded from sretoolbox

### PR DESCRIPTION
**Pull request by maorfr**
following up on https://github.com/app-sre/sretoolbox/pull/61, we can now consume threaded from sretoolbox.

### CODE REVIEW

**Comment by maorfr** [comment]
testing jira link: https://issues.redhat.com/browse/APPSRE-3914

**Comment by maorfr** [comment]
maybe like this? APPSRE-3914

**Comment by maorfr** [comment]
FAIL Required test coverage of 27.35% not reached. Total coverage: 27.28%

**Review by Piojo — APPROVED** [review]

**Review by geoberle — APPROVED** [review]

**Comment by maorfr** [comment]
blocked on https://github.com/app-sre/sretoolbox/pull/63

**Pull request merged**
