### PR TITLE
Quay membership must fail on missing users

### PR DESCRIPTION
**Pull request by rporres**
Nobody cares about warning messages, only about failed PR checks

Signed-off-by: Rafa Porres Molina <rporresm@redhat.com>

### CODE REVIEW

**Review by maorfr — APPROVED** [review]
LGTM

assuming you tested this locally, since i don't understand the exact behavior of `AggregatedDiffRunner`.

maybe @jmelis also wants to take a look?

**Comment by rporres** [comment]
Yes, I tested it locally. I had my issues understanding that class too. It was going to be your typical 5 minutes fix and then... 😂 

Assigning this to @jmelis , the father of the creature

**Comment by jmelis** [comment]
I will never stop apologizing to the universe for creating that class.

That said: @rporres if there is one missing user, you don't create any user whatsoever and exit. Other integrations apply whatever they can, and then they exit. I assume the reason why you did this is because the first place you are going to catch this is during PR checks with --dry-run, so it doesn't really matter in that scenario, but I think I would prefer to have it work the other way for 1) consistency 2) in case a user is deleted on the fly accidentally.

**Comment by rporres** [comment]
hmmm, we don't create the quay users with this integration, we just create the memberships. Having said that, I can address your (valid) concerns

**Review by jmelis — APPROVED** [review]
LGTM

**Pull request merged**
