### PR TITLE
move utils into reconcile, bump reconcile version to 1.0.0

### PR DESCRIPTION
**Pull request by maorfr**
as we want to publish qontract-reconcile in PyPi someday, this is a chore we will need to do.

### CODE REVIEW

**Review by apahim — APPROVED** [review]
Yes please!

**Comment by apahim** [comment]
And guess what: https://pypi.org/project/reconcile/

**Review by aditya-konarde — APPROVED** [review]
Lgtm! :)

**Comment by skryzhny** [comment]
LGTM

**Review by rporres — APPROVED** [review]
🕺

**Comment by maorfr** [comment]
replaced by #1301

**Pull request closed without merging**
