### PR TITLE
APPSRE-4029 simultaneous cluster upgrades

### PR DESCRIPTION
**Pull request by patjlm**
depends on https://github.com/app-sre/qontract-schemas/pull/96

### CODE REVIEW

**Comment by patjlm** [comment]
https://issues.redhat.com/browse/APPSRE-4029

**Comment by maorfr** [comment]
i have a couple of recommendations:
1. `ClusterUpgradeLockMap` - perhaps this can be generalized a bit? this is essentially a lock map using the State. maybe generalize the logic within it a bit and extract clusters specific information to the integration? i'd even go as far as implementing this `StateLockMap` in sretoolbox?
2. to avoid deadlocks i'd recommend we use `defer` for each unlock (immediately after locking).

**Comment by maorfr** [comment]
> Am I missing something

no, i was.

**Comment by patjlm** [comment]
@geoberle raised a very valid point that we may be able to do without a state to hold the lock map and rely exclusively on 
- upgradepolicies currently active in OCM
- the same upcoming locks mechanism implemented here (`new_locks`) to avoid 2 triggers in the same loop
This would simplify the overall implementation. I'll see what can be done.

Setting this as WIP in the meanwhile

**Comment by patjlm** [comment]
Following a discussion with @geoberle, I removed the need for a state-based lock map. The lock is now based on the simple presence of an `upgradePolicy` in OCM for each clusters. It should be much easier/leaner/cleaner this way.

**Review by geoberle — APPROVED** [review]
LVGTM

**Comment by patjlm** [comment]
renamed `locks` -> `mutexes` after discussion in https://github.com/app-sre/qontract-schemas/pull/96

**Review by rporres — APPROVED** [review]
Looks great. My only concern is allowing a free text for the mutexes and getting typo ruin the whole thing. As commented in https://github.com/app-sre/qontract-schemas/pull/96#pullrequestreview-908948880

You may want to create a ticket a solve it in subsequent PR

**Comment by patjlm** [comment]
> You may want to create a ticket a solve it in subsequent PR

https://issues.redhat.com/browse/APPSRE-4709

**Pull request merged**
