### PR TITLE
Bump reconcile builder image

### PR DESCRIPTION
**Pull request by andreugallofre**

### CODE REVIEW

**Comment by BumbleFeng** [comment]
I think you also need to update https://github.com/app-sre/qontract-reconcile/blob/master/dockerfiles/Dockerfile#L18 and  https://github.com/app-sre/qontract-reconcile/blob/master/dockerfiles/Dockerfile#L47

**Comment by andreugallofre** [comment]
Ported the changes from #2442 and now we can do the promotion in one go, @janboll ptal when you can 😄

**Comment by geoberle** [comment]
@andreugallofre the PR check is still failing because of `amtool` behaving a bit differently. see https://github.com/app-sre/qontract-reconcile/pull/2442#issuecomment-1149845535

**Comment by chassing** [comment]
superseded by #2463

**Pull request closed without merging**
