### PR TITLE
Constants module: DEFAULT_THREADS

### PR DESCRIPTION
**Pull request by apahim**
First version was quick and dirty, this version is thorough.

### CODE REVIEW

**Comment by maorfr** [comment]
a bit of a conflict with https://github.com/app-sre/qontract-reconcile/pull/896/files#diff-1b67c410afc746deccab16a054e4a5c9R135 perhaps?

**Comment by apahim** [comment]
yeah... too many defaults :/

**Comment by maorfr** [comment]
i guess we can do DEFAULT_THREADS=10 and A_LOT_OF_THREADS=20?

**Comment by apahim** [comment]
Dropping this. We are good for now.

**Pull request closed without merging**
