### PR TITLE
terrascript: add instance_requirements override to asg provider

### PR DESCRIPTION
**Pull request by croissanne**
Instead of listing image types to use in the ASG, instance_requirements support selecting instance types by vcpu and memory requirements. Certain instance types can be excluded if they're problematic for the workload.

### CODE REVIEW

**Comment by rporres** [comment]
This looks good, but it looks that `instance_requirements` is not yet supported by the [asg schema](https://github.com/app-sre/qontract-schemas/blob/main/schemas/aws/asg-defaults-1.yml), so you will need to add support for it.

**Comment by croissanne** [comment]
> This looks good, but it looks that `instance_requirements` is not yet supported by the [asg schema](https://github.com/app-sre/qontract-schemas/blob/main/schemas/aws/asg-defaults-1.yml), so you will need to add support for it.

Will do, I guess we open both in parallel and then merge at the same time? Or qontract reconcile needs support for it first, no?

**Comment by rporres** [comment]
qontract-reconcile needs support for it first. I'll merge/promote the schema, then I will merge/promote this.

**Review by rporres — APPROVED** [review]
schema changes merged and promoted. I will merge/promote this tomorrow.

**Comment by croissanne** [comment]
> schema changes merged and promoted. I will merge/promote this tomorrow.

Thanks! I'm not sure if I need to continue rebasing it or not ._.

**Comment by rporres** [comment]
no, no need to continue rebasing.

**Pull request merged**
